-- 08/08 -- wh_in + machine_pm + issue_log -- part of the production data import, see import_production_data.sql for full context.

begin;

insert into public.wh_in (whin_date, batch_id, brand_id, so_no, can_sum, can_hold, remark) values ('2026-07-01', '494MAMZ1', (select id from public.brands where brand_code = 'LSS'), '379969', 41000, 0, null);
insert into public.wh_in (whin_date, batch_id, brand_id, so_no, can_sum, can_hold, remark) values ('2026-07-01', '384MAMZ7O', (select id from public.brands where brand_code = 'PP'), '-', 11710, 0, null);
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-01', (select id from public.machines where machine_code = 'SM.04'), 'เปลี่ยนRollหัว4', '13:34:00', '13:36:00', 2, 'เปลี่ยนRollหัว4', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-01', (select id from public.machines where machine_code = 'SM.04'), 'ปรับwrinkleหัว2', '16:06:00', '16:09:00', 3, 'ปรับwrinkleหัว2', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-06', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '08:48:00', '08:50:00', 2, null, 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-06', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '08:56:00', '08:59:00', 3, null, 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-06', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '09:24:00', '09:36:00', 12, null, 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-10', (select id from public.machines where machine_code = 'DW.04'), 'ฝาไม่จ่าย', null, null, 3, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-10', (select id from public.machines where machine_code = 'SM.04'), 'ปรับ body hook หัว1', null, null, 11, 'ปรับ body hook หัว1', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-10', (select id from public.machines where machine_code = 'SM.02'), 'ปรับ corer hook หัว 3', null, null, 2, 'ปรับ corer hook', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-10', (select id from public.machines where machine_code = 'SM.01'), 'กระป๋องล้มหน้าเครื่อง', '15:20:00', null, 10, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-13', (select id from public.machines where machine_code = 'SM.04'), 'ปรับ chuck หัว 4', null, null, 5, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-13', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '04:12:00', null, 5, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-13', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', null, null, 3, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-16', (select id from public.machines where machine_code = 'SM.03'), 'ฝาไม่จ่าย', null, null, 8, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-18', (select id from public.machines where machine_code = 'SM.03'), 'กระป๋องล้ม', null, '13:00:00', 12, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-18', (select id from public.machines where machine_code = 'SM.03'), 'ฝาไม่จ่าย', '16:00:00', '16:05:00', 5, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-20', (select id from public.machines where machine_code = 'SF.03'), 'ปั๊มเสีย', null, null, 2, 'เปลี่ยนปั๊ม', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-20', (select id from public.machines where machine_code = 'SM.02'), 'ฝาไม่จ่าย', null, null, 5, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-20', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', null, null, 11, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-02', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '14:59:00', '15:16:00', 17, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-21', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '15:12:00', '15:21:00', 9, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-21', (select id from public.machines where machine_code = 'SM.04'), 'ฝาไม่จ่าย', '15:24:00', '15:27:00', 3, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.machine_pm (machinepm_date, machine_id, detail, start_time, end_time, downtime, solve, can_waste, employee) values ('2026-07-21', (select id from public.machines where machine_code = 'SM.03'), 'ฝาไม่จ่าย', '16:29:00', '16:32:00', 3, 'ปรับเครื่อง', 0, 'เอกชัย');
insert into public.issue_log (issue_date, department, reporter, detail, status) values ('2026-06-17', 'PD', 'System Admin', '3', 'แก้ไขแล้ว');
insert into public.issue_log (issue_date, department, reporter, detail, status) values ('2026-06-18', 'PD', 'System Admin', 'มอเตอร์เครื่องล้างกระป๋องรั่วแผนกช่างเข้ามาตรวจสอบแล้ว', 'รอแก้ไข');

commit;
